services:
  - type: web
    name: student-help-desk
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DRIVE_FOLDER_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
